# 010. PyTorch basic

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

device = "cuda:0" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [2]:
torch.__version__

'1.10.0+cu111'

## Tensor Data Types

<img src="https://miro.medium.com/max/875/1*-C10tKbZ2h0Zd7maau86oQ.png" height="400" />

### torch.tensor 함수

`tensor(data, dtype=None, device=None, requires_grad=False) -> Tensor`

     data (array_like): list, tuple, numpy ndarray, scalar, and other types.
     dtype :  `None`인 경우 `data`에서 데이터 유형을 유추합니다.  
     device : `cpu`, `cuda`  
     require_grad(bool, optional): autograd가 작업을 기록해야 하는 경우

Float torch tensor 생성

In [3]:
# numpy array 생성
a = np.ones((2, 3))
# tensor  생성
b = torch.tensor(a)
# dtype
print(a.dtype, '\t', b.dtype)

float64 	 torch.float64


In [4]:
# numpy 생성
a = np.ones((2, 3), dtype="float32")
# tensor 생성
b = torch.tensor(a)
# dtype
print(a.dtype, '\t', b.dtype)

float32 	 torch.float32


Integer tensor 생성

In [5]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32)
x

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [6]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32, device=device)
x

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0', dtype=torch.int32)

## 1D Tensor Operation

### tensor 생성

In [16]:
a = torch.tensor([7, 4, 3, 2, 6])

a[0], a[-1]

(tensor(7), tensor(6))

In [17]:
# cpu tensor
a = torch.FloatTensor([0, 1, 2, 3, 4])
a

tensor([0., 1., 2., 3., 4.])

In [18]:
# gpu tensor
a = torch.cuda.FloatTensor([0, 1, 2, 3, 4])
a

tensor([0., 1., 2., 3., 4.], device='cuda:0')

### Tensor Type 변환

- cpu <--> gpu

In [19]:
# cpu tensor
a = a.type(torch.FloatTensor)
a

tensor([0., 1., 2., 3., 4.])

In [20]:
# gpu tensor
b = a.to(device)
b

tensor([0., 1., 2., 3., 4.], device='cuda:0')

In [21]:
b = a.cuda()
b

tensor([0., 1., 2., 3., 4.], device='cuda:0')

In [22]:
c = a.type(torch.cuda.FloatTensor)
c

tensor([0., 1., 2., 3., 4.], device='cuda:0')

In [23]:
# cpu tensor
d = b.to("cpu")
d

tensor([0., 1., 2., 3., 4.])

In [24]:
e = c.cpu()
e

tensor([0., 1., 2., 3., 4.])

### Tensor 생성

- 무작위로 초기화된 행렬 생성 (uniform distribution)

In [25]:
x = torch.rand(5, 3) 
print(x)

tensor([[0.4871, 0.9493, 0.7188],
        [0.5605, 0.7596, 0.2449],
        [0.8778, 0.5198, 0.4648],
        [0.7723, 0.5491, 0.9735],
        [0.3668, 0.0275, 0.0534]])


- dtype이 long이고 0으로 채워진 행렬 생성

In [31]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
print(x.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64


- python list로 부터 tensor 생성

In [32]:
a = torch.tensor([7, 4, 3, 2, 6])
a.type(), a.dtype

('torch.LongTensor', torch.int64)

In [3]:
b = torch.FloatTensor([7, 4, 3, 2, 6])
b.type(), b.dtype

('torch.FloatTensor', torch.float32)

In [36]:
a == b

tensor([True, True, True, True, True])

torch.LongTensor --> torch.long, torch.int64

In [39]:
c = torch.tensor([7, 4, 3, 2, 6], dtype=torch.int64)
c

tensor([7, 4, 3, 2, 6])

In [40]:
d = torch.LongTensor([7, 4, 3, 2, 6])
d

tensor([7, 4, 3, 2, 6])

In [41]:
c == d

tensor([True, True, True, True, True])

## Tensor 의 shape & dimension (rank)

In [42]:
a = torch.Tensor([0, 1, 2, 3, 4])
a.size()

torch.Size([5])

In [43]:
# size() 와 shape 은 alias
a.shape

torch.Size([5])

In [44]:
a.ndimension()

1

## reshape
- torch.view : original tensor의 memory 공유 (contiguity 제한)
- torch.reshape: contiguity 제한 없음. 필요에 따라 new tensor 생성. numpy 와 유사한 operation을 위해 기능 제공

In [45]:
print(a)
print(a.view(5, 1))
print(a.reshape(5, 1))

tensor([0., 1., 2., 3., 4.])
tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])
tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])


In [46]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)        

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [47]:
x = torch.randn(4, 4)
y = x.reshape(16)
z = x.reshape(-1, 8)         

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [57]:
x = torch.randn(4, 4)
x

tensor([[ 0.2907,  0.5486, -1.2965, -0.0469],
        [-0.6631,  0.4156,  1.2260,  0.8707],
        [-0.8255,  0.5772,  1.8756, -1.5814],
        [-0.3479,  1.0278, -0.1813, -0.9822]])

In [49]:
x.is_contiguous()

True

In [61]:
# dim0, dim1 을 swap
x.transpose(0, 1)

tensor([[ 0.2907, -0.6631, -0.8255, -0.3479],
        [ 0.5486,  0.4156,  0.5772,  1.0278],
        [-1.2965,  1.2260,  1.8756, -0.1813],
        [-0.0469,  0.8707, -1.5814, -0.9822]])

In [62]:
x.transpose(0, 1).is_contiguous()

False

In [64]:
x.transpose(0, 1).reshape(-1, 8)

tensor([[ 0.2907, -0.6631, -0.8255, -0.3479,  0.5486,  0.4156,  0.5772,  1.0278],
        [-1.2965,  1.2260,  1.8756, -0.1813, -0.0469,  0.8707, -1.5814, -0.9822]])

In [65]:
x.transpose(0, 1).view(-1, 8)

RuntimeError: ignored

## numpy 와 tensor 간의 호환성

- memory 를 공유하므로 하나를 수정하면 나머지에 모두 반영  

In [66]:
numpy_array = np.array([0.0, 1.0, 2.0, 3.0, 4.0, 5.0])       # numpy array
torch_tensor = torch.from_numpy(numpy_array)               # torch tensor
torch_tensor 

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)

In [67]:
back_to_numpy = torch_tensor.numpy()           # numpy array
back_to_numpy

array([0., 1., 2., 3., 4., 5.])

In [68]:
numpy_array, torch_tensor, back_to_numpy

(array([0., 1., 2., 3., 4., 5.]),
 tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64),
 array([0., 1., 2., 3., 4., 5.]))

In [69]:
back_to_numpy[0] = 100

numpy_array, torch_tensor, back_to_numpy

(array([100.,   1.,   2.,   3.,   4.,   5.]),
 tensor([100.,   1.,   2.,   3.,   4.,   5.], dtype=torch.float64),
 array([100.,   1.,   2.,   3.,   4.,   5.]))

## Scalar value 

- 만약 tensor에 하나의 값만 존재한다면, ``.item()`` method를 사용하여 숫자 값을 얻을 수 있습니다.  

In [70]:
x = torch.randn(1)
x.item()

0.7250083684921265

In [71]:
a = torch.tensor([5., 3., 4., 1.])

print(a[0])
print(a[0].item())

tensor(5.)
5.0


- tensor 가 array 형태인 경우 `numpy()` method 를 통해 ndarray 반환

In [72]:
x = torch.randn(2)
print(x)
print()
print(x.numpy())

tensor([-0.5373,  0.6064])

[-0.53729224  0.60641265]


## Tensor 의 indexing & slicing

- Python 의 indexing & slicing 과 동일

In [76]:
c = torch.tensor([20, 1, 2, 3, 4])
c[0] = 100
c[4] = 0
c, c.dtype

(tensor([100,   1,   2,   3,   0]), torch.int64)

In [77]:
d = c[1:4]
d

tensor([1, 2, 3])

In [78]:
c[3:5] = torch.tensor([300.0, 400.0])
c

tensor([100,   1,   2, 300, 400])

## Basic Operations - numpy 와 동일

In [79]:
# element-wise 덧셈, 뺄셈 
u = torch.tensor([1.0, 0.0])
v = torch.tensor([0.0, 1.0])
z = u + v
z

tensor([1., 1.])

In [80]:
z = u - v
z

tensor([ 1., -1.])

In [81]:
# element-wise 곱셈
u = torch.tensor([1, 2])
v = torch.tensor([3, 2])
z = u * v
z

tensor([3, 4])

In [85]:
# mean, max, Standard Deviation
a = torch.tensor([1, -2, 3, 4, 5], dtype=torch.float32)

a.mean(), a.max(), a.std()

(tensor(2.2000), tensor(5.), tensor(2.7749))

## torch.linspace 와 np.linspace 비교

In [86]:
np_linspace = np.linspace(-2, 2, 5)
np_linspace

array([-2., -1.,  0.,  1.,  2.])

In [87]:
torch_linspace = torch.linspace(-2, 2, 5)
torch_linspace

tensor([-2., -1.,  0.,  1.,  2.])

## torch.arange 와 np.arange 비교

In [88]:
np.arange(-100, 100, 0.1)

array([-100. ,  -99.9,  -99.8, ...,   99.7,   99.8,   99.9])

In [89]:
torch.arange(-100, 100, 0.1)

tensor([-100.0000,  -99.9000,  -99.8000,  ...,   99.7000,   99.8000,
          99.9000])

## 2D Tensor Operation

In [2]:
_2d_tensor = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33], [41, 42, 43]])
_2d_tensor

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33],
        [41, 42, 43]])

- ndimension  
- shape  
- size()  
- numel (number of elements)

In [3]:
print(_2d_tensor)
print(_2d_tensor.ndimension())
print(_2d_tensor.shape)
print(_2d_tensor.size())
print(_2d_tensor.numel())

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33],
        [41, 42, 43]])
2
torch.Size([4, 3])
torch.Size([4, 3])
12


## matrix 간의 연산

In [4]:
x = torch.tensor([[1, 0], [0, 1]])
y = torch.tensor([[2, 1], [1, 2]])
print(x)
print(y)

tensor([[1, 0],
        [0, 1]])
tensor([[2, 1],
        [1, 2]])


- element-wise 연산

In [5]:
x * y

tensor([[2, 0],
        [0, 2]])

## matrix multiplication

In [6]:
x = torch.tensor([[0, 1, 1], [1, 0, 1]])
y = torch.tensor([[1, 1], [1, 1], [-1, 1]])

print(x)
print(y)

tensor([[0, 1, 1],
        [1, 0, 1]])
tensor([[ 1,  1],
        [ 1,  1],
        [-1,  1]])


In [7]:
torch.mm(x, y)

tensor([[0, 2],
        [0, 2]])

In [9]:
np.matmul(x.numpy(), y.numpy())

array([[0, 2],
       [0, 2]], dtype=int64)

### Concatenation

- default - first axis(row-wise)로 concatenate
- column-wise로 concatenate 하려면 axis=1 로 지정

In [10]:
x_1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
x_2 = torch.tensor([[7, 8, 9], [10, 11, 12]])
print(x_1)
print(x_2)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [11]:
torch.cat([x_1, x_2])

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [12]:
torch.cat([x_1, x_2], axis=1)

tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])

### torch.sum, torch.max, torch.min, torch.argmax, torch.argmin

- torch.sum(input, dim, keepdim=False, dtype=None) → Tensor  
주어진 차원 dim에서 입력 텐서의 각 행의 합(max, min)을 반환합니다.

- dim 을 지정한 경우, 지정된 dim을 축소하는 것입니다. 따라서 dim 0(행)을 접으면 하나의 행이 됩니다(열 단위로 합산).

In [13]:
x = torch.tensor([
     [1, 2, 3],
     [4, 5, 6]
   ])
x.shape

torch.Size([2, 3])

In [14]:
torch.sum(x)

tensor(21)

In [15]:
torch.sum(x, dim=0)

tensor([5, 7, 9])

In [16]:
torch.sum(x, dim=1)

tensor([ 6, 15])

In [17]:
torch.max(x, axis=0), torch.min(x, axis=0)

(torch.return_types.max(
 values=tensor([4, 5, 6]),
 indices=tensor([1, 1, 1])),
 torch.return_types.min(
 values=tensor([1, 2, 3]),
 indices=tensor([0, 0, 0])))

In [18]:
torch.max(x, axis=1), torch.min(x, axis=1)

(torch.return_types.max(
 values=tensor([3, 6]),
 indices=tensor([2, 2])),
 torch.return_types.min(
 values=tensor([1, 4]),
 indices=tensor([0, 0])))

In [19]:
torch.argmax(x), torch.argmin(x)

(tensor(5), tensor(0))

In [20]:
torch.argmax(x, axis=0), torch.argmin(x, axis=0)

(tensor([1, 1, 1]), tensor([0, 0, 0]))

In [21]:
torch.argmax(x, axis=1), torch.argmin(x, axis=1)

(tensor([2, 2]), tensor([0, 0]))

## TORCH.AUTOGRAD를 이용한 자동 미분

- autograd 패키지는 Tensor의 모든 연산에 대해 자동 미분을 제공   

- 신경망을 훈련할 때 가장 자주 사용되는 알고리즘은 역전파이다. 이 알고리즘에서 매개 변수 (모델 가중치)는 주어진 매개 변수에 대한 손실 함수의 기울기에 따라 조정된다.  

- 이러한 그래디언트를 계산하기 위해 PyTorch에는 torch.autograd라는 내장 미분 엔진이 있다.

- ``.requires_grad`` 속성을 True 로 설정하면, 그 tensor에서 이뤄진 모든 연산들을 추적(track)하기 시작  

- 계산이 완료된 후 ``.backward()`` 를 호출하여 모든 변화도(gradient)를 자동으로 계산  

- 이 Tensor의 변화도는 ``.grad`` 속성에 누적  

- Tensor가 기록을 추적하는 것을 중단하게 하려면, ``.detach()`` 를 호출하여 연산 기록으로부터 분리(detach)하여 이후 연산들이 추적되는 것을 방지한다.

- 도함수를 계산하기 위해서는 Tensor 의 ``.backward()`` 를 호출

In [22]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [23]:
y = x ** 2
y

tensor(4., grad_fn=<PowBackward0>)

y 를 x 에 대하여 미분  
$$y(x)=x^2$$ 

$$\frac{dy(x=2)}{dx}=2x=4 \rightarrow {y.backward()}$$  

In [24]:
y.backward()

x.grad

tensor(4.)

## 편미분 
$$f(u, v) = uv + u^2$$

$$\frac{\partial{f(u, v)}}{\partial {u}}=v+2u$$
$$\frac{\partial{f(u, v)}}{\partial {v}}=u$$

In [25]:
u = torch.tensor(1.0, requires_grad=True)
v = torch.tensor(2.0, requires_grad=True)

f = u * v + u ** 2
f

tensor(3., grad_fn=<AddBackward0>)

In [26]:
f.backward()

In [27]:
print(u.grad)
print(v.grad)

tensor(4.)
tensor(1.)


## backpropagation

In [31]:
import torch

x = torch.ones(5)    # input tensor
y = torch.zeros(3)   # expected output

w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)

z = torch.matmul(x, w)+b

loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
loss

tensor(1.0915, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

### Gradient 계산 

- 신경망에서 매개변수의 가중치를 최적화하려면 매개변수에 대한 손실 함수의 미분을 계산해야한다. 즉, x 및 y 의 일부 고정 값 아래에서 $\frac{\partial loss}{\partial w}$가 필요. 이러한 미분을 계산하려면 loss.backward ()를 호출 한 다음 w.grad 및 b.grad에서 값을 구한다.

In [119]:
loss.backward()
print("w 의 기울기 = ", w.grad)
print("b 의 기울기 = ", b.grad)

w 의 기울기 =  tensor([[0.0241, 0.2394, 0.2977],
        [0.0241, 0.2394, 0.2977],
        [0.0241, 0.2394, 0.2977],
        [0.0241, 0.2394, 0.2977],
        [0.0241, 0.2394, 0.2977]])
b 의 기울기 =  tensor([0.0241, 0.2394, 0.2977])


### 그라디언트 추적 비활성화

기본적으로 requires_grad=True 인 모든 텐서는 계산 기록을 추적하고 기울기 계산을 지원한다. 이를 수행 할 필요가 없는 경우, 즉 네트워크를 통해 순방향 계산만 수행하려는 경우 계산 코드를 torch.no_grad() 블록으로 둘러 싸서 계산 추적을 중지할 수 있다.

그래디언트 추적을 비활성화 해야하는 경우는 다음과 같다.  

    - pre-train 된 network 를 fine tuning 하는 경우  
    - 기울기를 추적하지 않는 텐서에 대한 계산이 더 효율적이기 때문에 순방향 패스 만 수행할 때 계산 속도를 높인다.

In [120]:
z = torch.matmul(x, w) + b

print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
    
print(z.requires_grad)

True
False


- 동일한 결과를 얻는 또 다른 방법은 텐서에서 detach() 메서드를 사용하는 것

In [121]:
z = torch.matmul(x, w)+b
z_det = z.detach()

print(z_det.requires_grad)

False


### CUDA Tensors

- .to 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있습니다.

In [122]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cuda', index=0)

In [123]:
x = torch.ones(2, 2)
x

tensor([[1., 1.],
        [1., 1.]])

In [124]:
x = x.to(device)
x

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [125]:
y = torch.ones((2, 3), device=device)  # GPU 상에 직접적으로 tensor를 생성
y

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')